INSERT INTO PATIENT (PID, DOB, Fname, Minit, Lname) 
VALUES (125, 2000-01-01, "John", "D", "Smith");

INSERT INTO EMPLOYEE (EID, SSN, Fname, Minit, Lname) 
VALUES (14, 22222222222, "Mister", "E", "Employee");

INSERT INTO IN_CLERK (CID, EID) 
VALUES (1014, 14);

INSERT INTO VISIT (V_id, Visit_time, Initial_cost, Additional_cost, Patient_id, Clerk_Id) 
VALUES (103, '2020-12-0 00:00:00', 10, 100, 125, 1014);

INSERT INTO MEDICAL_CONDITION(Cm_code, Name)
VALUES("mp3","Music");

INSERT INTO EMPLOYEE (EID, SSN, Fname, Minit, Lname) 
VALUES (15, 00000000000, "Default", "E", "Employee");

INSERT INTO SERVICE_PROVIDER (SID, EID)
VALUES (1015, 15);

INSERT INTO DIAGNOSIS(`Cm_code`,`Visit_Id`,`Provider_Id`) 
VALUES("mp3", 103, 1015);

SELECT PATIENT.Fname, VISIT.V_id, Cm_Code, SID, EID
FROM PATIENT, VISIT, DIAGNOSIS, SERVICE_PROVIDER
WHERE PATIENT.PID = VISIT.Patient_id
AND VISIT.V_id = DIAGNOSIS.Visit_Id
AND DIAGNOSIS.Provider_Id = SERVICE_PROVIDER.SID;

INSERT INTO SERVICE_PROVIDER (SID, EID)
VALUES (1016, 14);

INSERT INTO MEDICAL_CONDITION(Cm_code, Name)
VALUES("mp4","Video");

INSERT INTO DIAGNOSIS(`Cm_code`,`Visit_Id`,`Provider_Id`) 
VALUES("mp4", 103, 1016);

SELECT Fname, CID, SID FROM SERVICE_PROVIDER, EMPLOYEE, IN_CLERK
WHERE SERVICE_PROVIDER.EID = EMPLOYEE.EID
AND EMPLOYEE.EID = IN_CLERK.EID;
