# Creating DIAGNOSIS table
# Author: Grant Colestock

CREATE TABLE DIAGNOSIS (
	Cm_code VARCHAR(7) NOT NULL,
    Visit_Id INT NOT NULL,
    Provider_Id INT NOT NULL,
	PRIMARY KEY (Cm_code, Visit_Id),
    FOREIGN KEY (Cm_code) REFERENCES MEDICAL_CONDITION(Cm_code),
	FOREIGN KEY (Visit_Id) REFERENCES VISIT(V_id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (Provider_Id) REFERENCES SERVICE_PROVIDER(SID)
)