# Creating NURSE table
# Author: Team 25

CREATE TABLE NURSE (
	NID INT NOT NULL,
	EID INT NOT NULL UNIQUE,
    PRIMARY KEY (NID, EID),
    FOREIGN KEY (EID) REFERENCES EMPLOYEE(EID) ON DELETE CASCADE ON UPDATE CASCADE
)